# Generated by Django 2.2.13 on 2020-10-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0009_climtechimage_file_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="climtechimage",
            name="exif_datetime",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="climtechimage",
            name="md5_hash",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
