# Generated by Django 3.2.16 on 2022-10-05 20:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0011_streamfield_use_json_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="climtechimage",
            name="exif_datetime",
        ),
        migrations.RemoveField(
            model_name="climtechimage",
            name="md5_hash",
        ),
    ]
