# Generated by Django 5.0.9 on 2024-11-25 07:03

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0001_initial"),
        ("images", "0001_initial"),
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.climtechimage",
            ),
        ),
        migrations.AddField(
            model_name="blogindexpage",
            name="listing_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image to display along with summary, when this page is linked from elsewhere in the site.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.climtechimage",
            ),
        ),
        migrations.AddField(
            model_name="blogindexpage",
            name="social_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image to appear alongside 'Meta description', particularly for sharing on social networks",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.climtechimage",
                verbose_name="Meta image",
            ),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="blog.author",
            ),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="taxonomy.category",
            ),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="listing_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image to display along with summary, when this page is linked from elsewhere in the site.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.climtechimage",
            ),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="main_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.climtechimage",
            ),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="social_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image to appear alongside 'Meta description', particularly for sharing on social networks",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.climtechimage",
                verbose_name="Meta image",
            ),
        ),
        migrations.AddField(
            model_name="blogpagerelatedpage",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="blog.blogpage",
            ),
        ),
        migrations.AddField(
            model_name="blogpagerelatedpage",
            name="parent",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_posts",
                to="blog.blogpage",
            ),
        ),
        migrations.AddField(
            model_name="featuredpost",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="blog.blogpage",
            ),
        ),
        migrations.AddField(
            model_name="featuredpost",
            name="parent",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="featured_posts",
                to="blog.blogindexpage",
            ),
        ),
    ]
