# Generated by Django 5.0.9 on 2024-11-25 07:03

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteWideAlertSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sitewide_alert_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Enable sitewide alert"
                    ),
                ),
                (
                    "sitewide_alert_text",
                    wagtail.fields.RichTextField(blank=True, verbose_name="Alert text"),
                ),
                (
                    "background_colour",
                    models.CharField(
                        blank=True,
                        help_text="Background RGB value. e.g. <code>fd5765</code>",
                        max_length=6,
                    ),
                ),
                (
                    "text_colour",
                    models.CharField(
                        blank=True,
                        help_text="Text colour RGB value. e.g. <code>ffffff</code>",
                        max_length=6,
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sitewide alert",
            },
        ),
    ]
