# Generated by Django 5.0.9 on 2025-01-30 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mapsnippet",
            old_name="map_categories",
            new_name="body",
        ),
    ]
