# Generated by Django 5.0.9 on 2025-01-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_map_categories_mapsnippet_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mapsnippet",
            name="description",
        ),
        migrations.RemoveField(
            model_name="mapsnippet",
            name="subheading",
        ),
        migrations.RemoveField(
            model_name="mapsnippet",
            name="title",
        ),
        migrations.AddField(
            model_name="mapsnippet",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
