# Generated by Django 5.0.9 on 2025-02-10 20:28

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_mapsnippet_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mapsnippet",
            name="body",
            field=wagtail.fields.StreamField(
                [("map_block", 8)],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title for the map", "max_length": 255},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "blank": True,
                            "help_text": "Subheading (optional)",
                            "max_length": 255,
                            "null": True,
                        },
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Description of the map",
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Category Name", "max_length": 255, "required": True},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Hex code for category color", "required": True},
                    ),
                    5: (
                        "climtech.core.blocks.MultiChoiceBlock",
                        (),
                        {
                            "choices": [
                                ("dz", "Algeria"),
                                ("ao", "Angola"),
                                ("bj", "Benin"),
                                ("bw", "Botswana"),
                                ("bf", "Burkina Faso"),
                                ("bi", "Burundi"),
                                ("cm", "Cameroon"),
                                ("cv", "Cape Verde"),
                                ("cf", "Central African Republic"),
                                ("td", "Chad"),
                                ("km", "Comoros"),
                                ("cg", "Congo - Brazzaville"),
                                ("cd", "Congo - Kinshasa"),
                                ("ci", "Côte d'Ivoire"),
                                ("dj", "Djibouti"),
                                ("eg", "Egypt"),
                                ("gq", "Equatorial Guinea"),
                                ("er", "Eritrea"),
                                ("sz", "Eswatini"),
                                ("et", "Ethiopia"),
                                ("ga", "Gabon"),
                                ("gm", "Gambia"),
                                ("gh", "Ghana"),
                                ("gn", "Guinea"),
                                ("gw", "Guinea-Bissau"),
                                ("ke", "Kenya"),
                                ("ls", "Lesotho"),
                                ("lr", "Liberia"),
                                ("ly", "Libya"),
                                ("mg", "Madagascar"),
                                ("mw", "Malawi"),
                                ("ml", "Mali"),
                                ("mr", "Mauritania"),
                                ("mu", "Mauritius"),
                                ("ma", "Morocco"),
                                ("mz", "Mozambique"),
                                ("na", "Namibia"),
                                ("ne", "Niger"),
                                ("ng", "Nigeria"),
                                ("rw", "Rwanda"),
                                ("st", "São Tomé and Príncipe"),
                                ("sn", "Senegal"),
                                ("sc", "Seychelles"),
                                ("sl", "Sierra Leone"),
                                ("so", "Somalia"),
                                ("za", "South Africa"),
                                ("ss", "South Sudan"),
                                ("sd", "Sudan"),
                                ("tz", "Tanzania"),
                                ("tg", "Togo"),
                                ("tn", "Tunisia"),
                                ("ug", "Uganda"),
                                ("zm", "Zambia"),
                                ("zw", "Zimbabwe"),
                            ]
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("category_name", 3), ("color", 4), ("countries", 5)]],
                        {},
                    ),
                    7: ("wagtail.blocks.ListBlock", (6,), {"min_num": 1}),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 0),
                                ("subheading", 1),
                                ("description", 2),
                                ("map_categories", 7),
                            ]
                        ],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
