# Generated by Django 5.0.9 on 2025-02-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_mapsnippet_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signupformsnippet",
            name="name",
            field=models.CharField(
                help_text="For internal identification e.g 'This Week in ClimHub', 'TWIC'.",
                max_length=255,
            ),
        ),
    ]
