# Generated by Django 5.0.9 on 2024-11-09 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_alter_contentpage_body_alter_homepage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="code_snippet",
        ),
    ]
