# Generated by Django 5.0.9 on 2024-11-18 08:26

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0074_remove_mapsnippet_map_categories_alter_homepage_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mapsnippet",
            name="description",
            field=wagtail.fields.RichTextField(help_text="Description of the map"),
        ),
    ]
