# Generated by Django 5.0.9 on 2024-11-22 23:30

import wagtail_color_panel.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_alter_mapsnippet_map_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesetting',
            name='accent_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, default='#09aaff', help_text='Accent color (use color picker). Accent colors are often bright or contrasting to stand out', max_length=7, null=True),
        ),
    ]
