# Generated by Django 5.0.9 on 2024-11-25 07:03

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bullet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("text", wagtail.fields.RichTextField()),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FeatureAspect",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("video_url", models.URLField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FeatureDescription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("introduction", models.CharField(blank=True, max_length=255)),
                ("documentation_link", models.URLField(blank=True, max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FeatureIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "subheading",
                    models.TextField(blank=True, verbose_name="Sub heading"),
                ),
                (
                    "features",
                    wagtail.fields.StreamField(
                        [("features", 9)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"max_length": 255}),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Feature heading",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link", "document"],
                                    "label": "Feature description",
                                    "required": True,
                                },
                            ),
                            3: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"label": "Feature link", "required": False},
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "View docs",
                                    "label": "Feature link title",
                                    "max_length": 50,
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 1),
                                        ("description", 2),
                                        ("link", 3),
                                        ("link_title", 4),
                                    ]
                                ],
                                {},
                            ),
                            6: ("wagtail.blocks.ListBlock", (5,), {"min_num": 2}),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 0), ("features", 6)]],
                                {},
                            ),
                            8: ("wagtail.blocks.ListBlock", (7,), {}),
                            9: ("wagtail.blocks.StructBlock", [[("blocks", 8)]], {}),
                        },
                    ),
                ),
                (
                    "cta",
                    wagtail.fields.StreamField(
                        [("cta", 5)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "CTA text",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "CTA page", "required": False},
                            ),
                            2: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"label": "CTA URL", "required": False},
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 0), ("cta_page", 1), ("cta_url", 2)]],
                                {},
                            ),
                            4: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "label": "Short description",
                                    "max_length": 100,
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("cta", 3), ("description", 4)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="FeaturePageFeatureAspect",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
