# Generated by Django 5.0.9 on 2024-11-25 07:03

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_initial"),
        ("features", "0001_initial"),
        ("images", "0001_initial"),
        ("wagtailmedia", "0004_duration_optional_floatfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="featureaspect",
            name="screenshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.climtechimage",
            ),
        ),
        migrations.AddField(
            model_name="featureaspect",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailmedia.media",
            ),
        ),
        migrations.AddField(
            model_name="bullet",
            name="snippet",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bullets",
                to="features.featureaspect",
            ),
        ),
        migrations.AddField(
            model_name="featureindexpage",
            name="get_started",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.getstartedsnippet",
            ),
        ),
        migrations.AddField(
            model_name="featurepagefeatureaspect",
            name="feature_aspect",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="features.featureaspect",
            ),
        ),
        migrations.AddField(
            model_name="featurepagefeatureaspect",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feature_aspects",
                to="features.featuredescription",
            ),
        ),
    ]
