# Generated by Django 3.2.8 on 2022-01-28 09:49

from django.db import migrations

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0002_add_about"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packagespage",
            name="about_text",
            field=wagtail.fields.RichTextField(
                default="<p> Projects listed on Climtech are <i>third-party</i> packages.<br/> They are not vetted nor endorsed by Climtech.<br/> Use them at your own risk.</p>"
            ),
        ),
    ]
