# Generated by Django 5.0.9 on 2024-11-09 20:50

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0003_alter_packagespage_about_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packagespage",
            name="about_text",
            field=wagtail.fields.RichTextField(),
        ),
    ]
