# Generated by Django 5.0.9 on 2024-11-25 07:03

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_initial"),
        ("images", "0001_initial"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(
                        editable=False, help_text="GitHub milestone number", unique=True
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("CLOSED", "Closed")],
                        editable=False,
                        max_length=32,
                    ),
                ),
                ("due_on", models.DateField(blank=True, editable=False, null=True)),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField(verbose_name="URL")),
            ],
            options={
                "verbose_name": "roadmap milestone",
                "verbose_name_plural": "roadmap milestones",
                "ordering": ["-due_on"],
            },
        ),
        migrations.CreateModel(
            name="MilestoneItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "sponsorship_url",
                    models.URLField(
                        blank=True,
                        help_text="Custom URL to use for the 'Sponsor this' label",
                        verbose_name="Sponsorship URL",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(
                        editable=False, help_text="GitHub issue number", unique=True
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("CLOSED", "Closed")],
                        editable=False,
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "labels",
                    models.TextField(
                        blank=True, help_text="Comma-separated list of labels"
                    ),
                ),
                (
                    "milestone",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="roadmap.milestone",
                    ),
                ),
            ],
            options={
                "verbose_name": "roadmap milestone item",
                "verbose_name_plural": "roadmap milestone items",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="RoadmapPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "social_text",
                    models.CharField(
                        blank=True,
                        help_text="Description of this page as it should appear when shared on social networks, or in Google results",
                        max_length=255,
                        verbose_name="Meta description",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(blank=True, verbose_name="Intro"),
                ),
                ("fine_print", wagtail.fields.RichTextField(blank=True)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("rich_text", 1),
                            ("text_and_media", 10),
                            ("headline", 14),
                            ("highlight", 18),
                            ("teaser", 22),
                            ("icon_bullets", 27),
                            ("cards", 32),
                            ("logo_cards", 37),
                            ("cta", 38),
                            ("standalone_cta", 40),
                            ("standalone_quote", 42),
                            ("multiple_quotes", 45),
                            ("get_started_block", 46),
                            ("sign_up_form", 47),
                            ("comparison_table", 50),
                            ("logos", 53),
                            ("video", 55),
                        ],
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "bold",
                                        "italic",
                                        "h2",
                                        "h3",
                                        "ol",
                                        "ul",
                                        "link",
                                        "document",
                                    ],
                                    "required": True,
                                },
                            ),
                            1: ("wagtail.blocks.StructBlock", [[("rich_text", 0)]], {}),
                            2: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            3: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {"required": False},
                            ),
                            4: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {"default": False, "required": False},
                            ),
                            5: ("wagtail.blocks.TextBlock", (), {"required": True}),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "CTA text",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "CTA page", "required": False},
                            ),
                            8: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"label": "CTA URL", "required": False},
                            ),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 6), ("cta_page", 7), ("cta_url", 8)]],
                                {},
                            ),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("image", 2),
                                        ("embed", 3),
                                        ("image_on_right", 4),
                                        ("heading", 5),
                                        ("description", 5),
                                        ("cta", 9),
                                    ]
                                ],
                                {},
                            ),
                            11: ("wagtail.blocks.CharBlock", (), {"max_length": 255}),
                            12: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            13: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("arrow-alt", "Arrow alt"),
                                        ("arrow-in-circle", "Arrow in circle"),
                                        ("arrow-in-square", "Arrow in square"),
                                        ("arrows", "Arrows"),
                                        ("blog", "Blog"),
                                        ("bread", "Bread"),
                                        ("briefcase", "Briefcase"),
                                        ("building", "Building"),
                                        ("calendar", "Calendar"),
                                        ("code-file", "Code File"),
                                        ("document", "Document"),
                                        ("envelope", "Envelope"),
                                        ("explanation", "Explanation"),
                                        ("eye", "Eye"),
                                        ("flame", "Flame"),
                                        ("friends", "Friends"),
                                        ("github", "Github"),
                                        ("handshake", "Handshake"),
                                        ("heart", "Heart"),
                                        ("history", "History"),
                                        ("id-card", "ID Card"),
                                        ("image", "Image"),
                                        ("knife-fork", "Knife Fork"),
                                        ("leaf", "Leaf"),
                                        ("location-pin", "Location Pin"),
                                        ("map", "Map"),
                                        ("magnifying-glass", "Magnifying Glass"),
                                        ("money", "Money"),
                                        ("moon", "Moon"),
                                        ("one-two-steps", "One Two Steps"),
                                        ("padlock", "Padlock"),
                                        ("paper-plane", "Paper Plane"),
                                        ("paper-stack", "Paper Stack"),
                                        ("pen-checkbox", "Pen Checkbox"),
                                        ("person-in-tie", "Person in Tie"),
                                        ("python", "Python"),
                                        (
                                            "question-mark-circle",
                                            "Question Mark Circle",
                                        ),
                                        ("quotes", "Quotes"),
                                        ("release-cycle", "Release Cycle"),
                                        ("roadmap", "Roadmap"),
                                        ("rocket", "Rocket"),
                                        ("rollback", "Rollback"),
                                        ("slack", "Slack"),
                                        ("speech-bubble", "Speech Bubble"),
                                        ("sun-cloud", "Sun Cloud"),
                                        ("table-tennis", "Table Tennis"),
                                        ("tree", "Tree"),
                                        ("wordpress", "Wordpress"),
                                        ("world", "World"),
                                    ],
                                    "required": False,
                                },
                            ),
                            14: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 11),
                                        ("sub_heading", 12),
                                        ("intro", 12),
                                        ("cta", 9),
                                        ("icon", 13),
                                        ("dark_background", 4),
                                    ]
                                ],
                                {},
                            ),
                            15: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                            16: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            17: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 50, "required": False},
                            ),
                            18: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 15),
                                        ("description", 12),
                                        ("image", 16),
                                        ("image_on_right", 4),
                                        ("meta_text", 17),
                                        ("meta_icon", 13),
                                        ("cta", 9),
                                    ]
                                ],
                                {},
                            ),
                            19: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"page_type": ["blog.BlogPage"], "required": False},
                            ),
                            20: ("wagtail.blocks.URLBlock", (), {"required": False}),
                            21: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "label": "Subheading for external link",
                                    "required": False,
                                },
                            ),
                            22: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("page", 19),
                                        ("url_chooser", 20),
                                        ("image_for_external_link", 2),
                                        ("heading_for_external_link", 12),
                                        ("subheading_for_ext_link", 21),
                                    ]
                                ],
                                {},
                            ),
                            23: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("arrow-alt", "Arrow alt"),
                                        ("arrow-in-circle", "Arrow in circle"),
                                        ("arrow-in-square", "Arrow in square"),
                                        ("arrows", "Arrows"),
                                        ("blog", "Blog"),
                                        ("bread", "Bread"),
                                        ("briefcase", "Briefcase"),
                                        ("building", "Building"),
                                        ("calendar", "Calendar"),
                                        ("code-file", "Code File"),
                                        ("document", "Document"),
                                        ("envelope", "Envelope"),
                                        ("explanation", "Explanation"),
                                        ("eye", "Eye"),
                                        ("flame", "Flame"),
                                        ("friends", "Friends"),
                                        ("github", "Github"),
                                        ("handshake", "Handshake"),
                                        ("heart", "Heart"),
                                        ("history", "History"),
                                        ("id-card", "ID Card"),
                                        ("image", "Image"),
                                        ("knife-fork", "Knife Fork"),
                                        ("leaf", "Leaf"),
                                        ("location-pin", "Location Pin"),
                                        ("map", "Map"),
                                        ("magnifying-glass", "Magnifying Glass"),
                                        ("money", "Money"),
                                        ("moon", "Moon"),
                                        ("one-two-steps", "One Two Steps"),
                                        ("padlock", "Padlock"),
                                        ("paper-plane", "Paper Plane"),
                                        ("paper-stack", "Paper Stack"),
                                        ("pen-checkbox", "Pen Checkbox"),
                                        ("person-in-tie", "Person in Tie"),
                                        ("python", "Python"),
                                        (
                                            "question-mark-circle",
                                            "Question Mark Circle",
                                        ),
                                        ("quotes", "Quotes"),
                                        ("release-cycle", "Release Cycle"),
                                        ("roadmap", "Roadmap"),
                                        ("rocket", "Rocket"),
                                        ("rollback", "Rollback"),
                                        ("slack", "Slack"),
                                        ("speech-bubble", "Speech Bubble"),
                                        ("sun-cloud", "Sun Cloud"),
                                        ("table-tennis", "Table Tennis"),
                                        ("tree", "Tree"),
                                        ("wordpress", "Wordpress"),
                                        ("world", "World"),
                                    ]
                                },
                            ),
                            24: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "required": False,
                                },
                            ),
                            25: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon", 23),
                                        ("heading", 11),
                                        ("description", 24),
                                        ("cta", 9),
                                    ]
                                ],
                                {},
                            ),
                            26: ("wagtail.blocks.ListBlock", (25,), {}),
                            27: (
                                "wagtail.blocks.StructBlock",
                                [[("icon_bullets", 26)]],
                                {"icon": "rectangle-list"},
                            ),
                            28: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"features": ["bold", "italic"], "required": False},
                            ),
                            29: ("wagtail.blocks.TextBlock", (), {"max_length": 50}),
                            30: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 11),
                                        ("description", 28),
                                        ("meta_icon", 23),
                                        ("meta_text", 29),
                                        ("cta", 9),
                                    ]
                                ],
                                {},
                            ),
                            31: ("wagtail.blocks.ListBlock", (30,), {}),
                            32: (
                                "wagtail.blocks.StructBlock",
                                [[("cards", 31)]],
                                {"group": "Cards", "icon": "table-list"},
                            ),
                            33: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 255, "required": False},
                            ),
                            34: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Heading", "max_length": 255},
                            ),
                            35: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("text", 34),
                                        ("description", 28),
                                        ("meta_icon", 23),
                                        ("meta_text", 29),
                                        ("logo", 2),
                                        ("cta_page", 7),
                                        ("cta_url", 8),
                                    ]
                                ],
                                {},
                            ),
                            36: ("wagtail.blocks.ListBlock", (35,), {}),
                            37: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 33), ("cards", 36)]],
                                {"group": "Cards", "icon": "images"},
                            ),
                            38: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 6), ("cta_page", 7), ("cta_url", 8)]],
                                {"group": "Call to action"},
                            ),
                            39: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "label": "Short description",
                                    "max_length": 100,
                                    "required": False,
                                },
                            ),
                            40: (
                                "wagtail.blocks.StructBlock",
                                [[("cta", 9), ("description", 39)]],
                                {"group": "Call to action"},
                            ),
                            41: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"features": ["link"], "required": True},
                            ),
                            42: (
                                "wagtail.blocks.StructBlock",
                                [[("quote", 5), ("author", 41), ("author_image", 2)]],
                                {"group": "Quotes"},
                            ),
                            43: (
                                "wagtail.blocks.StructBlock",
                                [[("quote", 5), ("author", 41), ("author_image", 2)]],
                                {},
                            ),
                            44: ("wagtail.blocks.ListBlock", (43,), {"min_num": 2}),
                            45: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 5), ("quotes", 44)]],
                                {"group": "Quotes"},
                            ),
                            46: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                ("core.GetStartedSnippet",),
                                {
                                    "icon": "table-list",
                                    "template": "patterns/components/streamfields/get_started_block/get_started_block.html",
                                },
                            ),
                            47: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                ("core.SignupFormSnippet",),
                                {
                                    "icon": "envelope-open-text",
                                    "template": "patterns/components/streamfields/sign_up_form_block/sign_up_form_block.html",
                                },
                            ),
                            48: (
                                "wagtail.blocks.StreamBlock",
                                [[("rich_text", 24), ("image", 2)]],
                                {"max_num": 1, "required": False},
                            ),
                            49: (
                                "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                                [[("content", 48)]],
                                {},
                            ),
                            50: (
                                "wagtail.blocks.StructBlock",
                                [[("comparison_table", 49)]],
                                {},
                            ),
                            51: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            52: ("wagtail.blocks.ListBlock", (16,), {}),
                            53: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 51), ("logos", 52)]],
                                {"group": "Logos"},
                            ),
                            54: (
                                "wagtailmedia.blocks.VideoChooserBlock",
                                (),
                                {"required": False},
                            ),
                            55: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 51), ("video", 54), ("embed", 3)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "social_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image to appear alongside 'Meta description', particularly for sharing on social networks",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.climtechimage",
                        verbose_name="Meta image",
                    ),
                ),
                (
                    "sponsorship_page",
                    models.ForeignKey(
                        blank=True,
                        help_text="This will be used as the default link for the 'Sponsor this' label",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.contentpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
