# Generated by Django 5.0.9 on 2024-11-25 07:03

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicesPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", models.TextField(blank=True, null=True)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("section", 18)],
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"form_classname": "title", "required": True},
                            ),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("astronaut", "Astronaut"),
                                        ("cloud", "Cloud"),
                                        ("money-check", "Money check"),
                                        ("tools", "Tools"),
                                    ],
                                    "required": False,
                                },
                            ),
                            2: (
                                "climtech.services.blocks.SectionMediaBlock",
                                (),
                                {"required": False},
                            ),
                            3: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "help_text": "Section image is used as a fallback when no media is defined.",
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Rendered below the image/media",
                                    "label": "Section image/media caption",
                                    "required": False,
                                },
                            ),
                            5: ("climtech.services.blocks.SubheadingBlock", (), {}),
                            6: ("climtech.services.blocks.DividerBlock", (), {}),
                            7: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"features": ["bold", "italic", "link", "ul", "ol"]},
                            ),
                            8: ("climtech.services.blocks.CardsBlock", (), {}),
                            9: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Text leading up the action text of the button.",
                                    "max_length": 50,
                                    "required": False,
                                },
                            ),
                            10: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Emphasised text for the button action.",
                                    "max_length": 50,
                                    "required": True,
                                },
                            ),
                            11: ("wagtail.blocks.URLBlock", (), {"required": True}),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [[("lead_text", 9), ("action_text", 10), ("link", 11)]],
                                {},
                            ),
                            13: ("wagtail.blocks.TextBlock", (), {"required": True}),
                            14: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            15: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Additional information about the source. E.g. a persons job title and company.",
                                    "required": False,
                                },
                            ),
                            16: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 13), ("source", 14), ("reference", 15)]],
                                {},
                            ),
                            17: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("subheading", 5),
                                        ("divider", 6),
                                        ("paragraph", 7),
                                        ("cards", 8),
                                        ("link_button", 12),
                                        ("quote", 16),
                                    ]
                                ],
                                {"required": False},
                            ),
                            18: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 0),
                                        ("icon", 1),
                                        ("section_media", 2),
                                        ("section_image", 3),
                                        ("section_image_caption", 4),
                                        ("content", 17),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
